### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [Sturke/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by Sturke** [comment]
I'm Burke Stanion
I live in Central Illinois near the University of Illinois
I love Mexican food, usually of the South West. Green Chili is what belongs on a burrito.
I love growing my own vegetables. This year, I'm trying indoor hydroponics for the first time.
